Updated auto gen for the new gcan requirements
gopher-motorsports/gophercan-lib pull request #56
Opened 2021-05-24 02:51 UTC by caljay98

Also uses the global .yaml file

2021-05-24 02:56 UTC, caljay98 commented
- I ripped the whole gophercannon folder from the "adding_sesnsors" branch, I thought that was the most up to date. It should make merging easier in the future
- A new python script called gcan_auto_gen.py was created to do this task, I thought it would be better to have two separate scripts that could work off of the same file
- gophercannon.py does not reflect the changes needed for the new auto-gen files. @hocally lets chat on how to put those back together
- go4-22c.yaml will need to be updated to support some of the features of the new auto-gen. An issue will be created

2021-05-25 01:12 UTC, caljay98 commented
Also adding the filter bug to this PR

2021-06-05 18:00 UTC, hocally requested changes

2021-06-05 18:00 UTC, hocally commented on GopherCAN.c
> -	filt_id_low = this_module_id << (CAN_ID_SIZE - DEST_POS - DEST_SIZE);
Nit: why

2021-06-05 18:00 UTC, hocally commented on GopherCAN.c
> +    filt_mask_low = GET_ID_LOW(filt_mask_low);
Nit: alignment

2021-06-05 18:00 UTC, hocally commented on GopherCAN.h
> +#define GET_ID_HIGH(id) (((id) << 3) >> 16) & 0xffff
Should surround these macro defs with parans to avoid any order of precedence issues

2021-06-05 18:00 UTC, hocally commented on gophercannon/automation/build_networks.sh
> +python3 gophercannon.py networks/go4-22c.yaml -r -n -s -t $TRANSIENT_DURATION -w $WOBBLE_AMOUNT
This is on me, but this should end in a newline

2021-06-05 18:00 UTC, hocally commented on gophercannon/gcan_auto_gen.py
> +repo_hash = 0x0123456789ABCD
I'm assuming this is WIP but this can be pulled in via the git python package

2021-06-05 18:00 UTC, hocally commented on gophercannon/outputs/GopherCAN_ACM.h
> +#ifndef GOPHERCAN_ACM_H
I don't think autogened files should be checked in to git

2021-06-05 18:00 UTC, hocally commented on gophercannon/outputs/GopherCAN_Common.h
> +#ifndef GOPHERCAN_COMMON_H
Same as ACM comment

2021-06-05 18:00 UTC, hocally commented on gophercannon/outputs/GopherCAN_DAM.h
> +#ifndef GOPHERCAN_DAM_H
Same as ACM comment

2021-06-05 18:00 UTC, hocally commented on gophercannon/outputs/GopherCAN_ids.c
> +// End of GopherCAN_ids.c
Autogen should be updated so there is a newline at the end of the file

2021-06-05 18:01 UTC, hocally commented
@caljay98 Generally looks good, but shouldn't merge without fixing the macro parens issue

2021-06-06 17:51 UTC, merged